# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180928_1646'),
        ('goods', '0006_auto_20180928_1844'),
    ]

    operations = [
    ]
